#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/spiffytech/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

parcellite &
~/bin/swap-escape.sh
xset b off
synclient MaxTapTime=0
synclient TapButton1=0
synclient TapButton2=0
synclient TapButton3=0
nm-applet &
xscreensaver &
# Dropbox nukes disk throughput on boot, start it later
#sleep 300 && dropbox start
./btsync
redshift -l 36:-78.9 -v -t 6500:3700 &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/spiffytech/.fluxbox/log"
